AUTH_PATH = "./auth"
FRIENDS_PATH = "./friends"
GAME_PATH = "./game"
GATEWAY_PATH = "./gateway"
PROFIL = "./profil"
CMD_FORMAT = format

format:
	${MAKE} ${CMD_FORMAT} -C ${AUTH_PATH}
	${MAKE} ${CMD_FORMAT} -C ${FRIENDS_PATH}
	${MAKE} ${CMD_FORMAT} -C ${GAME_PATH}
	${MAKE} ${CMD_FORMAT} -C ${GATEWAY_PATH}
	${MAKE} ${CMD_FORMAT} -C ${PROFIL}

.PHONY: format