services:
  cert-generator:
    image: alpine/openssl
    container_name: cert_generator
    entrypoint: ""
    volumes:
      - ./scripts:/scripts
      - certs_data:/etc/certs
    command: ["/bin/sh", "-c", "/scripts/generate-certs.sh && chmod 0640 /etc/certs/nginx.key && chmod 0644 /etc/certs/nginx.crt && echo 'Cert generator finished'"]
    labels:
      - "container_name=cert_generator"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
      - "8043:443"
    networks:
      - frontend-net
    volumes:
      - certs_data:/etc/certs:ro
      - profile_pictures:/usr/share/nginx/html/uploads/profile_pictures
    depends_on:
      gateway:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "container_name=frontend"

  prometheus:
    image: prom/prometheus:v3.2.0
    container_name: prometheus
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      cadvisor:
        condition: service_started
    restart: unless-stopped
    networks:
      - transcendance-net
    labels:
      - "container_name=prometheus"
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    expose:
      - 8080
    volumes:
      # - /run/user/102787/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - transcendance-net
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      gateway:
        condition: service_healthy
    labels:
      - "container_name=cadvisor"

  grafana:
    image: grafana/grafana:10.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/dashboard-provisioning.yaml:/etc/grafana/provisioning/dashboards/dashboard-provisioning.yaml
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - certs_data:/etc/certs:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/certs/nginx.crt
      - GF_SERVER_CERT_KEY=/etc/certs/nginx.key
      - GF_SERVER_HTTP_PORT=3000
    depends_on:
      prometheus:
        condition: service_started
    restart: unless-stopped
    networks:
      - transcendance-net
    labels:
      - "container_name=grafana"

  gateway:
    build: 
      context: ./backend/gateway
      args:
        - GATEWAY_PORT=${GATEWAY_PORT:-8085}
    container_name: gateway
    env_file:
      - .env
    environment:
      - SSL_KEY_PATH=/etc/certs/nginx.key
      - SSL_CERT_PATH=/etc/certs/nginx.crt
      - GATEWAY_PORT=${GATEWAY_PORT:-8085}
    ports:
      - "${GATEWAY_PORT:-8085}:${GATEWAY_PORT:-8085}"
    expose:
      - 9464
    networks:
      - frontend-net
      - transcendance-net
    volumes:
      - profile_pictures:/app/uploads
      - certs_data:/etc/certs:ro
    depends_on:
      auth:
        condition: service_healthy
      profile:
        condition: service_healthy
      friends:
        condition: service_healthy
      game:
        condition: service_healthy
      cert-generator:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://gateway:${GATEWAY_PORT:-8085}/api/v1/health"]
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5
    restart: unless-stopped
    labels:
      - "container_name=gateway"
  profile:
    build: ./backend/profile
    container_name: profile
    env_file:
      - .env
    expose:
      - 8081
      - 9464
    networks:
      - transcendance-net
    volumes:
      - profile_pictures:/app/uploads
    restart: unless-stopped
    labels:
      - "container_name=profile"
  auth:
    build: ./backend/auth
    container_name: auth
    env_file:
      - .env
    expose:
      - 8082
      - 9464
    networks:
      - transcendance-net
    volumes:
      - db:/app/db
    restart: unless-stopped
    depends_on:
      game:
        condition: service_healthy
    labels:
      - "container_name=auth"
  game:
    build: ./backend/game
    container_name: game
    env_file:
      - .env
    expose:
      - 8083
      - 9464
    networks:
      - transcendance-net
    volumes:
      - db:/app/db
    restart: unless-stopped
    labels:
      - "container_name=game"
  friends:
    build: ./backend/friends
    container_name: friends
    env_file:
      - .env
    expose:
      - 8084
      - 9464
    networks:
      - transcendance-net
    volumes:
      - db:/app/db
    restart: unless-stopped
    labels:
      - "container_name=friends"

volumes:
  certs_data:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/sgoinfre/data/db/
  profile_pictures:
  auth:
  friends:
  game:
  prometheus_data:
  grafana_data:

networks:
  transcendance-net:
    driver: bridge
  frontend-net:
    driver: bridge

##42 volumes mount
# volumes:
#   certs_data:
#     driver: local
#     driver_opts:
#       type: none
#       device: "/home/bboissen/sgoinfre/certs_data"
#       o: bind
#   profile_pictures:
#     driver: local
#     driver_opts:
#       type: none
#       device: "/home/bboissen/sgoinfre/profile_pictures"
#       o: bind

