{
 "title": "Docker metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load average",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{container_label_com_docker_compose_container_number=\"1\"}",
     "legendFormat": "{{container_label_container_name}}"
    }
   ]
  },
  {
   "title": "Memory usage excluding cache",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{container_label_com_docker_compose_project=\"transcendence\"} / 1048576",
     "legendFormat": "{{container_label_container_name}}"
    }
   ]
  },
  {
   "title": "Cache usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_cache{container_label_com_docker_compose_project=\"transcendence\"} / 1048576",
     "legendFormat": "{{container_label_container_name}}"
    }
   ]
  },
  {
   "title": "MB received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{container_label_com_docker_compose_project=\"transcendence\", interface=\"eth0\"} / 1048576",
     "legendFormat": "{{container_label_container_name}}"
    }
   ]
  },
  {
   "title": "MB transmitted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{container_label_com_docker_compose_project=\"transcendence\", interface=\"eth0\"} / 1048576",
     "legendFormat": "{{container_label_container_name}}"
    }
   ]
  }
 ]
}