{
 "title": "Game service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SELECT operation time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(medium_query_duration_bucket{operation=\"SELECT\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(fast_query_duration_bucket{operation=\"SELECT\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "SELECT operation time (slow)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(slow_query_duration_bucket{operation=\"SELECT\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "INSERT operation time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(medium_query_duration_bucket{operation=\"INSERT\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(fast_query_duration_bucket{operation=\"INSERT\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(slow_query_duration_bucket{operation=\"INSERT\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "HTTP request duration - Game service",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_server_duration_bucket{http_method=\"GET\", net_host_name!=\"host.docker.internal\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}} - {{http_method}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(http_server_duration_bucket{http_method=\"POST\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}} - {{http_method}}"
    }
   ]
  },
  {
   "title": "HTTP request count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"200\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"201\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code!=\"201\", http_status_code!=\"200\", http_status_code!=\"204\", http_status_code!=\"304\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"204\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"304\"})",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}