{
 "title": "Game stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total number of matches",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "match_creation_total{match_status=\"created\", job=\"game-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of incomplete match",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Average match duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Average goal duration",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Total goals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(match_id) (goal_duration_seconds_count{job=\"game-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goal duration distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "goal_duration_seconds_bucket{le!=\"+Inf\", job=\"game-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elo distribution",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elo_creation_bucket{job=\"game-service\", le!=\"+Inf\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}