services:
  api:
    build: ./requirements/api
    container_name: api
    environment:
      - API_ADDR="0.0.0.0"
      - API_PORT="8080"
      - PROFIL_PORT="8081"
      - AUTH_PORT="8082"
      - FRIENDS_PORT="8084"
      - UPLOADS_DIR="./uploads"
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - transcendance-net
    volumes:
      - uploads-volume:/app/uploads
    restart: always
  profil:
    build: ./requirements/profil
    container_name: profil
    environment:
      - PROFIL_ADDR="profil"
      - PROFIL_PORT="8081"
    env_file:
      - .env
    expose:
      - 8081
    networks:
      - transcendance-net
    volumes:
      - uploads-volume:/app/uploads
    restart: always
  auth:
    build: ./requirements/auth
    container_name: auth
    environment:
      - AUTH_ADDR="auth"
      - AUTH_PORT="8082"
    env_file:
      - .env
    expose:
      - 8082
    networks:
      - transcendance-net
    volumes:
      - dev-volume:/app/db
    restart: always
  # game:
  #   build: ./requirements/game
  #   container_name: game
  #   expose:
  #     - 8083
  #   networks:
  #     - transcendance-net
  #   restart: always
  friends:
    build: ./requirements/friends
    container_name: friends
    environment:
      - FRIENDS_ADDR="friends"
      - FRIENDS_PORT="8084"
    env_file:
      - .env
    expose:
      - 8084
    networks:
      - transcendance-net
    volumes:
      - dev-volume:/app/db
    restart: always

networks:
  transcendance-net:
    driver: bridge

volumes:
  uploads-volume: 
  dev-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/Documents/db