services:
  api_gateway:
    build: ./requirements/api_gateway
    container_name: api_gateway
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - transcendance-net
    volumes:
      - uploads-volume:/app/uploads
    restart: always
  profil:
    build: ./requirements/profil
    container_name: profil
    env_file:
      - .env
    expose:
      - 8081
    networks:
      - transcendance-net
    volumes:
      - uploads-volume:/app/uploads
    restart: always
  auth:
    build: ./requirements/auth
    container_name: auth
    env_file:
      - .env
    expose:
      - 8082
    networks:
      - transcendance-net
    volumes:
      - dev-volume:/app/db
    restart: always
  # game:
  #   build: ./requirements/game
  #   container_name: game
  #   expose:
  #     - 8083
  #   networks:
  #     - transcendance-net
  #   restart: always
  friends:
    build: ./requirements/friends
    container_name: friends
    env_file:
      - .env
    expose:
      - 8084
    networks:
      - transcendance-net
    volumes:
      - dev-volume:/app/db
    restart: always

networks:
  transcendance-net:
    driver: bridge

volumes:
  uploads-volume: 
  dev-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/Documents/db