global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['cadvisor:8090']
    
  - job_name: 'game-service'
    static_configs:
      - targets: ['host.docker.internal:9464']
    metrics_path: '/metrics'