{
 "title": "Auth stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total number of user created",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_creation_total{job=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of 2FA activation",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twofa_enabled_counter_total{job=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of JWT generated",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jwt_generation_total{job=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of JWT revoked",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jwt_revocation_total{job=\"auth-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}