{
 "title": "Friends service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SELECT operation time - Friends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(medium_query_duration_bucket{operation=\"SELECT\", job=\"friends-service\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "INSERT operation time - Friends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(medium_query_duration_bucket{operation=\"INSERT\", job=\"friends-service\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "UPDATE operation time - Friends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(medium_query_duration_bucket{operation=\"UPDATE\", job=\"friends-service\"}[$__rate_interval]))",
     "legendFormat": "{{table}}"
    }
   ]
  },
  {
   "title": "HTTP request duration - Friends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_server_duration_bucket{http_method=\"GET\", job=\"friends-service\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}} - {{http_method}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(http_server_duration_bucket{http_method=\"POST\", job=\"friends-service\"}[$__rate_interval]))",
     "legendFormat": "{{http_route}} - {{http_method}}"
    }
   ]
  },
  {
   "title": "HTTP request count - Friends",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"200\", job=\"friends-service\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"201\", job=\"friends-service\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code!=\"201\", http_status_code!=\"200\", http_status_code!=\"204\", http_status_code!=\"304\", job=\"friends-service\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"204\", job=\"friends-service\"})",
     "legendFormat": "{{http_status_code}}"
    },
    {
     "expr": "sum by(http_status_code) (http_server_duration_count{http_status_code=\"304\", job=\"friends-service\"})",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  }
 ]
}