CREATE TABLE IF NOT EXISTS friends (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  id_1 VARCHAR(32) NOT NULL,
  id_2 VARCHAR(32) NOT NULL,
  accepted BOOLEAN NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
